version: '3.8'  # Specifies the Docker Compose file version

services:
  fastapi-app:
    build:
      context: .  # Specifies the directory containing the Dockerfile
    ports:
      - "8000:8000"  # Maps port 8000 on the host to port 8000 on the container
    environment:
      PYTHONUNBUFFERED: 1
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      JWT_SECRET: ${JWT_SECRET}   
       
    volumes:
      - .:/app  
    command: uvicorn main:app --host 0.0.0.0 --port 8000  

