name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add host key to known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "Running ssh-keyscan..."
        ssh-keyscan -H ${{ secrets.EC2_HOST }} > ~/.ssh/known_hosts 2> ssh-keyscan-error.log
        if [ $? -ne 0 ]; then
          echo "ssh-keyscan failed. Error output:"
          cat ssh-keyscan-error.log
          exit 1
        fi
        echo "Known hosts file content:"
        cat ~/.ssh/known_hosts


    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no -v ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo Connected successfully"

    - name: Copy files to EC2
      run: |
        rsync -avz --exclude '.git/*' --exclude '.github/*' ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/myapp
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "cd /home/ubuntu/myapp && docker-compose up -d --build"

    - name: Run Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "cd /home/ubuntu/myapp && docker-compose up -d --build"
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
